name : Buid and Deploy Code
#define the trigger
on: [push,pull_request]

jobs:
  job1: #defines the os 
    runs-on: ubuntu-latest
    steps: #defines what steps to do 
    - name: pulling git repo
      uses: actions/checkout@v2
    - name: say hi to me
      run: echo "hi meiemdms" #to do a custom command




