name : Buid and Deploy Code
#define the trigger
on: [push,pull_request]

jobs:
  job1: #defines the os 
    runs-on: ubuntu-latest
    steps: #defines what steps to do 
    - name: pulling git repo
      uses: actions/checkout@v2
    - name: say hi to me
      run: echo "hi meiemdms" #to do a custom command
    - name: install python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: update pip
      run: python -m pip install --upgrade pip
    - name: install all dependences
      run: pip install -r requirement.txt
    - name: test with pytest
      run: 
        pip install pytest
        pytest 




